indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack
    - url: https://volochek.life
      name: Volochek
    - url: https://nikoartgallery.com
      name: NikoArtGallery

server:
  port: 8080
spring:
  datasource:
    username: root
    password: 3101
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false

visit-settings:
  userAgent: SearchableSearchBot
  referrer: http://www.google.com